#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const soundsDir = __dirname;
const outPath = path.join(soundsDir, "sfx_pcm_data.h");
const sampleRate = 16000;

function sanitizeBaseName(fileName) {
  const stem = fileName.replace(/\.mp3$/i, "");
  const clean = stem
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return clean.length ? clean : "clip";
}

function formatBytes(buffer) {
  const lines = [];
  for (let i = 0; i < buffer.length; i += 16) {
    const chunk = [];
    for (let j = i; j < Math.min(i + 16, buffer.length); j++) {
      chunk.push(`0x${buffer[j].toString(16).padStart(2, "0")}`);
    }
    lines.push(`  ${chunk.join(", ")},`);
  }
  return lines.join("\n");
}

function decodeToPcmU8(fullPath) {
  return execFileSync("ffmpeg", [
    "-hide_banner",
    "-loglevel",
    "error",
    "-i",
    fullPath,
    "-ac",
    "1",
    "-ar",
    String(sampleRate),
    "-af",
    "volume=0.85",
    "-f",
    "u8",
    "-acodec",
    "pcm_u8",
    "pipe:1",
  ]);
}

const files = fs
  .readdirSync(soundsDir)
  .filter((name) => name.toLowerCase().endsWith(".mp3"))
  .sort((a, b) => a.localeCompare(b));

const clips = files.map((fileName) => {
  const fullPath = path.join(soundsDir, fileName);
  return {
    fileName,
    symbolBase: sanitizeBaseName(fileName),
    data: decodeToPcmU8(fullPath),
  };
});

const out = [];
out.push("#pragma once");
out.push("#include <Arduino.h>");
out.push("");
out.push("// Auto-generated from device_code/sounds/*.mp3");
out.push("// Generated by device_code/sounds/generate_sfx_pcm_header.js");
out.push(`// Embedded ${sampleRate} Hz mono unsigned 8-bit PCM for LEDC PWM playback.`);
out.push("");

for (const clip of clips) {
  out.push(`// ${clip.fileName} (${clip.data.length} samples)`);
  out.push(`const uint8_t sfx_${clip.symbolBase}_pcm[] PROGMEM = {`);
  out.push(formatBytes(clip.data));
  out.push("};");
  out.push(`const size_t sfx_${clip.symbolBase}_pcm_len = ${clip.data.length};`);
  out.push("");
}

out.push("typedef struct { const char* name; const uint8_t* data; size_t len; uint16_t sample_rate; } SfxPcm;");
out.push("static const SfxPcm SFX_PCM_LIST[] = {");
for (const clip of clips) {
  const stem = clip.fileName.replace(/\.mp3$/i, "");
  out.push(
    `  {"${stem}", sfx_${clip.symbolBase}_pcm, sfx_${clip.symbolBase}_pcm_len, ${sampleRate}},`
  );
}
out.push("};");
out.push("static const size_t SFX_PCM_COUNT = sizeof(SFX_PCM_LIST) / sizeof(SFX_PCM_LIST[0]);");
out.push("");

fs.writeFileSync(outPath, `${out.join("\n")}\n`);
console.log(`Generated ${path.relative(process.cwd(), outPath)} with ${clips.length} clip(s) at ${sampleRate} Hz.`);
