#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const soundsDir = __dirname;
const outPath = path.join(soundsDir, "sfx_pcm_data.h");
const sampleRate = 16000;
const pwmBits = 9;
const pwmMax = (1 << pwmBits) - 1;
const pcmMid = 1 << (pwmBits - 1);

function sanitizeBaseName(fileName) {
  const stem = fileName.replace(/\.mp3$/i, "");
  const clean = stem
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return clean.length ? clean : "clip";
}

function formatWords(words) {
  const lines = [];
  for (let i = 0; i < words.length; i += 12) {
    const chunk = [];
    for (let j = i; j < Math.min(i + 12, words.length); j++) {
      chunk.push(String(words[j]));
    }
    lines.push(`  ${chunk.join(", ")},`);
  }
  return lines.join("\n");
}

function decodeToPcmWords(fullPath) {
  const pcm = execFileSync("ffmpeg", [
    "-hide_banner",
    "-loglevel",
    "error",
    "-i",
    fullPath,
    "-ac",
    "1",
    "-ar",
    String(sampleRate),
    "-af",
    "volume=0.85",
    "-acodec",
    "pcm_s16le",
    "-f",
    "s16le",
    "pipe:1",
  ]);

  const words = [];
  for (let i = 0; i + 1 < pcm.length; i += 2) {
    const signed = pcm.readInt16LE(i);
    let duty = Math.round(pcmMid + (signed * pcmMid) / 32768);
    if (duty < 0) duty = 0;
    if (duty > pwmMax) duty = pwmMax;
    words.push(duty);
  }
  return words;
}

const files = fs
  .readdirSync(soundsDir)
  .filter((name) => name.toLowerCase().endsWith(".mp3"))
  .sort((a, b) => a.localeCompare(b));

const clips = files.map((fileName) => {
  const fullPath = path.join(soundsDir, fileName);
  return {
    fileName,
    symbolBase: sanitizeBaseName(fileName),
    data: decodeToPcmWords(fullPath),
  };
});

const out = [];
out.push("#pragma once");
out.push("#include <Arduino.h>");
out.push("");
out.push("// Auto-generated from device_code/sounds/*.mp3");
out.push("// Generated by device_code/sounds/generate_sfx_pcm_header.js");
out.push(`// Embedded ${sampleRate} Hz mono unsigned ${pwmBits}-bit PCM for LEDC PWM playback.`);
out.push("");

for (const clip of clips) {
  out.push(`// ${clip.fileName} (${clip.data.length} samples)`);
  out.push(`const uint16_t sfx_${clip.symbolBase}_pcm[] PROGMEM = {`);
  out.push(formatWords(clip.data));
  out.push("};");
  out.push(`const size_t sfx_${clip.symbolBase}_pcm_len = ${clip.data.length};`);
  out.push("");
}

out.push("typedef struct { const char* name; const uint16_t* data; size_t len; uint16_t sample_rate; } SfxPcm;");
out.push("static const SfxPcm SFX_PCM_LIST[] = {");
for (const clip of clips) {
  const stem = clip.fileName.replace(/\.mp3$/i, "");
  out.push(
    `  {"${stem}", sfx_${clip.symbolBase}_pcm, sfx_${clip.symbolBase}_pcm_len, ${sampleRate}},`
  );
}
out.push("};");
out.push("static const size_t SFX_PCM_COUNT = sizeof(SFX_PCM_LIST) / sizeof(SFX_PCM_LIST[0]);");
out.push("");

fs.writeFileSync(outPath, `${out.join("\n")}\n`);
console.log(`Generated ${path.relative(process.cwd(), outPath)} with ${clips.length} clip(s) at ${sampleRate} Hz / ${pwmBits} bits.`);
