#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const soundsDir = __dirname;
const outPath = path.join(soundsDir, "sfx_mp3_data.h");

function sanitizeBaseName(fileName) {
  const stem = fileName.replace(/\.mp3$/i, "");
  const clean = stem
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return clean.length ? clean : "clip";
}

function formatBytes(buffer) {
  const lines = [];
  for (let i = 0; i < buffer.length; i += 12) {
    const chunk = [];
    for (let j = i; j < Math.min(i + 12, buffer.length); j++) {
      chunk.push(`0x${buffer[j].toString(16).padStart(2, "0")}`);
    }
    lines.push(`  ${chunk.join(", ")},`);
  }
  return lines.join("\n");
}

const files = fs
  .readdirSync(soundsDir)
  .filter((name) => name.toLowerCase().endsWith(".mp3"))
  .sort((a, b) => a.localeCompare(b));

const clips = files.map((fileName) => {
  const fullPath = path.join(soundsDir, fileName);
  const data = fs.readFileSync(fullPath);
  return {
    fileName,
    symbolBase: sanitizeBaseName(fileName),
    data,
  };
});

const out = [];
out.push("#pragma once");
out.push("#include <Arduino.h>");
out.push("");
out.push("// Auto-generated from device_code/sounds/*.mp3");
out.push("// Generated by device_code/sounds/generate_sfx_header.js");
out.push("// Embedded MP3 byte streams for ESP32 MP3 decoder playback.");
out.push("");

for (const clip of clips) {
  out.push(`// ${clip.fileName} (${clip.data.length} bytes)`);
  out.push(`const uint8_t sfx_${clip.symbolBase}_mp3[] PROGMEM = {`);
  out.push(formatBytes(clip.data));
  out.push("};");
  out.push(`const size_t sfx_${clip.symbolBase}_mp3_len = ${clip.data.length};`);
  out.push("");
}

out.push("typedef struct { const char* name; const uint8_t* data; size_t len; } SfxMp3;");
out.push("static const SfxMp3 SFX_MP3_LIST[] = {");
for (const clip of clips) {
  const stem = clip.fileName.replace(/\.mp3$/i, "");
  out.push(
    `  {"${stem}", sfx_${clip.symbolBase}_mp3, sfx_${clip.symbolBase}_mp3_len},`
  );
}
out.push("};");
out.push("static const size_t SFX_MP3_COUNT = sizeof(SFX_MP3_LIST) / sizeof(SFX_MP3_LIST[0]);");
out.push("");

fs.writeFileSync(outPath, `${out.join("\n")}\n`);
console.log(`Generated ${path.relative(process.cwd(), outPath)} with ${clips.length} clip(s).`);
